/**
 * Localization System - Multi-language Support
 * Supports: English, Italian, Spanish, French, German, Portuguese, Russian, Japanese, Korean, Chinese, Arabic, Hindi
 */

export type SupportedLanguage = 
  | 'en' | 'it' | 'es' | 'fr' | 'de' | 'pt' 
  | 'ru' | 'ja' | 'ko' | 'zh' | 'ar' | 'hi';

export interface Translations {
  // Game UI
  level: string;
  score: string;
  time: string;
  hint: string;
  hints: string;
  shuffle: string;
  settings: string;
  coins: string;
  
  // Actions
  play: string;
  pause: string;
  resume: string;
  restart: string;
  quit: string;
  next: string;
  back: string;
  
  // Messages
  levelComplete: string;
  gameOver: string;
  newHighScore: string;
  wordFound: string;
  noHintsLeft: string;
  watchAdForHint: string;
  watchAdForCoins: string;
  
  // Menu
  home: string;
  levels: string;
  shop: string;
  profile: string;
  leaderboard: string;
  achievements: string;
  dailyChallenge: string;
  
  // Settings
  sound: string;
  music: string;
  vibration: string;
  notifications: string;
  language: string;
  
  // Shop
  removeAds: string;
  buyCoins: string;
  buyHints: string;
  restore: string;
  
  // Rewards
  dailyReward: string;
  claimReward: string;
  comeBackTomorrow: string;
  bonusCoins: string;
  freeHint: string;
  
  // Misc
  loading: string;
  enterWord: string;
  congratulations: string;
  amazing: string;
  excellent: string;
  great: string;
  good: string;
}

const translations: Record<SupportedLanguage, Translations> = {
  // English
  en: {
    level: 'Level',
    score: 'Score',
    time: 'Time',
    hint: 'Hint',
    hints: 'Hints',
    shuffle: 'Shuffle',
    settings: 'Settings',
    coins: 'Coins',
    play: 'Play',
    pause: 'Pause',
    resume: 'Resume',
    restart: 'Restart',
    quit: 'Quit',
    next: 'Next',
    back: 'Back',
    levelComplete: 'Level Complete!',
    gameOver: 'Game Over',
    newHighScore: 'New High Score!',
    wordFound: 'Word Found!',
    noHintsLeft: 'No hints left',
    watchAdForHint: 'Watch ad for free hint',
    watchAdForCoins: 'Watch ad for free coins',
    home: 'Home',
    levels: 'Levels',
    shop: 'Shop',
    profile: 'Profile',
    leaderboard: 'Leaderboard',
    achievements: 'Achievements',
    dailyChallenge: 'Daily Challenge',
    sound: 'Sound',
    music: 'Music',
    vibration: 'Vibration',
    notifications: 'Notifications',
    language: 'Language',
    removeAds: 'Remove Ads',
    buyCoins: 'Buy Coins',
    buyHints: 'Buy Hints',
    restore: 'Restore Purchases',
    dailyReward: 'Daily Reward',
    claimReward: 'Claim Reward',
    comeBackTomorrow: 'Come back tomorrow!',
    bonusCoins: 'Bonus Coins',
    freeHint: 'Free Hint',
    loading: 'Loading...',
    enterWord: 'Enter word...',
    congratulations: 'Congratulations!',
    amazing: 'Amazing!',
    excellent: 'Excellent!',
    great: 'Great!',
    good: 'Good!',
  },

  // Italian
  it: {
    level: 'Livello',
    score: 'Punteggio',
    time: 'Tempo',
    hint: 'Suggerimento',
    hints: 'Suggerimenti',
    shuffle: 'Mescola',
    settings: 'Impostazioni',
    coins: 'Monete',
    play: 'Gioca',
    pause: 'Pausa',
    resume: 'Riprendi',
    restart: 'Ricomincia',
    quit: 'Esci',
    next: 'Avanti',
    back: 'Indietro',
    levelComplete: 'Livello Completato!',
    gameOver: 'Game Over',
    newHighScore: 'Nuovo Record!',
    wordFound: 'Parola Trovata!',
    noHintsLeft: 'Nessun suggerimento rimasto',
    watchAdForHint: 'Guarda video per suggerimento',
    watchAdForCoins: 'Guarda video per monete',
    home: 'Home',
    levels: 'Livelli',
    shop: 'Negozio',
    profile: 'Profilo',
    leaderboard: 'Classifica',
    achievements: 'Obiettivi',
    dailyChallenge: 'Sfida Giornaliera',
    sound: 'Suoni',
    music: 'Musica',
    vibration: 'Vibrazione',
    notifications: 'Notifiche',
    language: 'Lingua',
    removeAds: 'Rimuovi Pubblicità',
    buyCoins: 'Compra Monete',
    buyHints: 'Compra Suggerimenti',
    restore: 'Ripristina Acquisti',
    dailyReward: 'Premio Giornaliero',
    claimReward: 'Riscatta Premio',
    comeBackTomorrow: 'Torna domani!',
    bonusCoins: 'Monete Bonus',
    freeHint: 'Suggerimento Gratis',
    loading: 'Caricamento...',
    enterWord: 'Inserisci parola...',
    congratulations: 'Congratulazioni!',
    amazing: 'Fantastico!',
    excellent: 'Eccellente!',
    great: 'Ottimo!',
    good: 'Bene!',
  },

  // Spanish
  es: {
    level: 'Nivel',
    score: 'Puntuación',
    time: 'Tiempo',
    hint: 'Pista',
    hints: 'Pistas',
    shuffle: 'Mezclar',
    settings: 'Ajustes',
    coins: 'Monedas',
    play: 'Jugar',
    pause: 'Pausa',
    resume: 'Continuar',
    restart: 'Reiniciar',
    quit: 'Salir',
    next: 'Siguiente',
    back: 'Atrás',
    levelComplete: '¡Nivel Completado!',
    gameOver: 'Fin del Juego',
    newHighScore: '¡Nueva Puntuación Alta!',
    wordFound: '¡Palabra Encontrada!',
    noHintsLeft: 'No quedan pistas',
    watchAdForHint: 'Ver anuncio para pista gratis',
    watchAdForCoins: 'Ver anuncio para monedas',
    home: 'Inicio',
    levels: 'Niveles',
    shop: 'Tienda',
    profile: 'Perfil',
    leaderboard: 'Clasificación',
    achievements: 'Logros',
    dailyChallenge: 'Desafío Diario',
    sound: 'Sonido',
    music: 'Música',
    vibration: 'Vibración',
    notifications: 'Notificaciones',
    language: 'Idioma',
    removeAds: 'Quitar Anuncios',
    buyCoins: 'Comprar Monedas',
    buyHints: 'Comprar Pistas',
    restore: 'Restaurar Compras',
    dailyReward: 'Recompensa Diaria',
    claimReward: 'Reclamar Recompensa',
    comeBackTomorrow: '¡Vuelve mañana!',
    bonusCoins: 'Monedas Extra',
    freeHint: 'Pista Gratis',
    loading: 'Cargando...',
    enterWord: 'Escribe palabra...',
    congratulations: '¡Felicidades!',
    amazing: '¡Increíble!',
    excellent: '¡Excelente!',
    great: '¡Genial!',
    good: '¡Bien!',
  },

  // French
  fr: {
    level: 'Niveau',
    score: 'Score',
    time: 'Temps',
    hint: 'Indice',
    hints: 'Indices',
    shuffle: 'Mélanger',
    settings: 'Paramètres',
    coins: 'Pièces',
    play: 'Jouer',
    pause: 'Pause',
    resume: 'Reprendre',
    restart: 'Recommencer',
    quit: 'Quitter',
    next: 'Suivant',
    back: 'Retour',
    levelComplete: 'Niveau Terminé!',
    gameOver: 'Fin de Partie',
    newHighScore: 'Nouveau Record!',
    wordFound: 'Mot Trouvé!',
    noHintsLeft: 'Plus d\'indices',
    watchAdForHint: 'Voir pub pour indice gratuit',
    watchAdForCoins: 'Voir pub pour pièces',
    home: 'Accueil',
    levels: 'Niveaux',
    shop: 'Boutique',
    profile: 'Profil',
    leaderboard: 'Classement',
    achievements: 'Succès',
    dailyChallenge: 'Défi Quotidien',
    sound: 'Son',
    music: 'Musique',
    vibration: 'Vibration',
    notifications: 'Notifications',
    language: 'Langue',
    removeAds: 'Supprimer Pubs',
    buyCoins: 'Acheter Pièces',
    buyHints: 'Acheter Indices',
    restore: 'Restaurer Achats',
    dailyReward: 'Récompense Quotidienne',
    claimReward: 'Réclamer',
    comeBackTomorrow: 'Revenez demain!',
    bonusCoins: 'Pièces Bonus',
    freeHint: 'Indice Gratuit',
    loading: 'Chargement...',
    enterWord: 'Entrez le mot...',
    congratulations: 'Félicitations!',
    amazing: 'Incroyable!',
    excellent: 'Excellent!',
    great: 'Super!',
    good: 'Bien!',
  },

  // German
  de: {
    level: 'Level',
    score: 'Punkte',
    time: 'Zeit',
    hint: 'Hinweis',
    hints: 'Hinweise',
    shuffle: 'Mischen',
    settings: 'Einstellungen',
    coins: 'Münzen',
    play: 'Spielen',
    pause: 'Pause',
    resume: 'Fortsetzen',
    restart: 'Neustart',
    quit: 'Beenden',
    next: 'Weiter',
    back: 'Zurück',
    levelComplete: 'Level Abgeschlossen!',
    gameOver: 'Spiel Vorbei',
    newHighScore: 'Neuer Highscore!',
    wordFound: 'Wort Gefunden!',
    noHintsLeft: 'Keine Hinweise mehr',
    watchAdForHint: 'Werbung für Hinweis ansehen',
    watchAdForCoins: 'Werbung für Münzen ansehen',
    home: 'Start',
    levels: 'Level',
    shop: 'Shop',
    profile: 'Profil',
    leaderboard: 'Rangliste',
    achievements: 'Erfolge',
    dailyChallenge: 'Tägliche Herausforderung',
    sound: 'Ton',
    music: 'Musik',
    vibration: 'Vibration',
    notifications: 'Benachrichtigungen',
    language: 'Sprache',
    removeAds: 'Werbung Entfernen',
    buyCoins: 'Münzen Kaufen',
    buyHints: 'Hinweise Kaufen',
    restore: 'Käufe Wiederherstellen',
    dailyReward: 'Tägliche Belohnung',
    claimReward: 'Belohnung Holen',
    comeBackTomorrow: 'Komm morgen wieder!',
    bonusCoins: 'Bonus Münzen',
    freeHint: 'Gratis Hinweis',
    loading: 'Laden...',
    enterWord: 'Wort eingeben...',
    congratulations: 'Gratulation!',
    amazing: 'Fantastisch!',
    excellent: 'Ausgezeichnet!',
    great: 'Toll!',
    good: 'Gut!',
  },

  // Portuguese
  pt: {
    level: 'Nível',
    score: 'Pontuação',
    time: 'Tempo',
    hint: 'Dica',
    hints: 'Dicas',
    shuffle: 'Embaralhar',
    settings: 'Configurações',
    coins: 'Moedas',
    play: 'Jogar',
    pause: 'Pausar',
    resume: 'Continuar',
    restart: 'Reiniciar',
    quit: 'Sair',
    next: 'Próximo',
    back: 'Voltar',
    levelComplete: 'Nível Completo!',
    gameOver: 'Fim de Jogo',
    newHighScore: 'Nova Pontuação Máxima!',
    wordFound: 'Palavra Encontrada!',
    noHintsLeft: 'Sem dicas restantes',
    watchAdForHint: 'Ver anúncio para dica grátis',
    watchAdForCoins: 'Ver anúncio para moedas',
    home: 'Início',
    levels: 'Níveis',
    shop: 'Loja',
    profile: 'Perfil',
    leaderboard: 'Ranking',
    achievements: 'Conquistas',
    dailyChallenge: 'Desafio Diário',
    sound: 'Som',
    music: 'Música',
    vibration: 'Vibração',
    notifications: 'Notificações',
    language: 'Idioma',
    removeAds: 'Remover Anúncios',
    buyCoins: 'Comprar Moedas',
    buyHints: 'Comprar Dicas',
    restore: 'Restaurar Compras',
    dailyReward: 'Recompensa Diária',
    claimReward: 'Resgatar',
    comeBackTomorrow: 'Volte amanhã!',
    bonusCoins: 'Moedas Bônus',
    freeHint: 'Dica Grátis',
    loading: 'Carregando...',
    enterWord: 'Digite a palavra...',
    congratulations: 'Parabéns!',
    amazing: 'Incrível!',
    excellent: 'Excelente!',
    great: 'Ótimo!',
    good: 'Bom!',
  },

  // Russian
  ru: {
    level: 'Уровень',
    score: 'Счёт',
    time: 'Время',
    hint: 'Подсказка',
    hints: 'Подсказки',
    shuffle: 'Перемешать',
    settings: 'Настройки',
    coins: 'Монеты',
    play: 'Играть',
    pause: 'Пауза',
    resume: 'Продолжить',
    restart: 'Заново',
    quit: 'Выйти',
    next: 'Далее',
    back: 'Назад',
    levelComplete: 'Уровень Пройден!',
    gameOver: 'Игра Окончена',
    newHighScore: 'Новый Рекорд!',
    wordFound: 'Слово Найдено!',
    noHintsLeft: 'Подсказок не осталось',
    watchAdForHint: 'Смотреть рекламу за подсказку',
    watchAdForCoins: 'Смотреть рекламу за монеты',
    home: 'Главная',
    levels: 'Уровни',
    shop: 'Магазин',
    profile: 'Профиль',
    leaderboard: 'Рейтинг',
    achievements: 'Достижения',
    dailyChallenge: 'Ежедневный Вызов',
    sound: 'Звук',
    music: 'Музыка',
    vibration: 'Вибрация',
    notifications: 'Уведомления',
    language: 'Язык',
    removeAds: 'Убрать Рекламу',
    buyCoins: 'Купить Монеты',
    buyHints: 'Купить Подсказки',
    restore: 'Восстановить Покупки',
    dailyReward: 'Ежедневная Награда',
    claimReward: 'Забрать',
    comeBackTomorrow: 'Возвращайтесь завтра!',
    bonusCoins: 'Бонусные Монеты',
    freeHint: 'Бесплатная Подсказка',
    loading: 'Загрузка...',
    enterWord: 'Введите слово...',
    congratulations: 'Поздравляем!',
    amazing: 'Потрясающе!',
    excellent: 'Отлично!',
    great: 'Супер!',
    good: 'Хорошо!',
  },

  // Japanese
  ja: {
    level: 'レベル',
    score: 'スコア',
    time: '時間',
    hint: 'ヒント',
    hints: 'ヒント',
    shuffle: 'シャッフル',
    settings: '設定',
    coins: 'コイン',
    play: 'プレイ',
    pause: '一時停止',
    resume: '再開',
    restart: 'やり直す',
    quit: '終了',
    next: '次へ',
    back: '戻る',
    levelComplete: 'レベルクリア！',
    gameOver: 'ゲームオーバー',
    newHighScore: 'ハイスコア更新！',
    wordFound: '単語発見！',
    noHintsLeft: 'ヒントがありません',
    watchAdForHint: '広告を見てヒントをゲット',
    watchAdForCoins: '広告を見てコインをゲット',
    home: 'ホーム',
    levels: 'レベル',
    shop: 'ショップ',
    profile: 'プロフィール',
    leaderboard: 'ランキング',
    achievements: '実績',
    dailyChallenge: 'デイリーチャレンジ',
    sound: 'サウンド',
    music: '音楽',
    vibration: 'バイブ',
    notifications: '通知',
    language: '言語',
    removeAds: '広告を削除',
    buyCoins: 'コインを購入',
    buyHints: 'ヒントを購入',
    restore: '購入を復元',
    dailyReward: 'デイリー報酬',
    claimReward: '受け取る',
    comeBackTomorrow: 'また明日！',
    bonusCoins: 'ボーナスコイン',
    freeHint: '無料ヒント',
    loading: '読み込み中...',
    enterWord: '単語を入力...',
    congratulations: 'おめでとう！',
    amazing: 'すごい！',
    excellent: '素晴らしい！',
    great: 'グレート！',
    good: 'いいね！',
  },

  // Korean
  ko: {
    level: '레벨',
    score: '점수',
    time: '시간',
    hint: '힌트',
    hints: '힌트',
    shuffle: '섞기',
    settings: '설정',
    coins: '코인',
    play: '플레이',
    pause: '일시정지',
    resume: '계속',
    restart: '다시 시작',
    quit: '종료',
    next: '다음',
    back: '뒤로',
    levelComplete: '레벨 완료!',
    gameOver: '게임 오버',
    newHighScore: '최고 점수 갱신!',
    wordFound: '단어 찾기 성공!',
    noHintsLeft: '힌트가 없습니다',
    watchAdForHint: '광고 보고 힌트 받기',
    watchAdForCoins: '광고 보고 코인 받기',
    home: '홈',
    levels: '레벨',
    shop: '상점',
    profile: '프로필',
    leaderboard: '순위표',
    achievements: '업적',
    dailyChallenge: '일일 도전',
    sound: '소리',
    music: '음악',
    vibration: '진동',
    notifications: '알림',
    language: '언어',
    removeAds: '광고 제거',
    buyCoins: '코인 구매',
    buyHints: '힌트 구매',
    restore: '구매 복원',
    dailyReward: '일일 보상',
    claimReward: '받기',
    comeBackTomorrow: '내일 다시 오세요!',
    bonusCoins: '보너스 코인',
    freeHint: '무료 힌트',
    loading: '로딩 중...',
    enterWord: '단어 입력...',
    congratulations: '축하합니다!',
    amazing: '대단해요!',
    excellent: '훌륭해요!',
    great: '좋아요!',
    good: '잘했어요!',
  },

  // Chinese (Simplified)
  zh: {
    level: '关卡',
    score: '分数',
    time: '时间',
    hint: '提示',
    hints: '提示',
    shuffle: '打乱',
    settings: '设置',
    coins: '金币',
    play: '开始',
    pause: '暂停',
    resume: '继续',
    restart: '重新开始',
    quit: '退出',
    next: '下一个',
    back: '返回',
    levelComplete: '关卡完成！',
    gameOver: '游戏结束',
    newHighScore: '新纪录！',
    wordFound: '找到单词！',
    noHintsLeft: '没有提示了',
    watchAdForHint: '观看广告获取提示',
    watchAdForCoins: '观看广告获取金币',
    home: '主页',
    levels: '关卡',
    shop: '商店',
    profile: '个人资料',
    leaderboard: '排行榜',
    achievements: '成就',
    dailyChallenge: '每日挑战',
    sound: '音效',
    music: '音乐',
    vibration: '振动',
    notifications: '通知',
    language: '语言',
    removeAds: '移除广告',
    buyCoins: '购买金币',
    buyHints: '购买提示',
    restore: '恢复购买',
    dailyReward: '每日奖励',
    claimReward: '领取',
    comeBackTomorrow: '明天再来！',
    bonusCoins: '奖励金币',
    freeHint: '免费提示',
    loading: '加载中...',
    enterWord: '输入单词...',
    congratulations: '恭喜！',
    amazing: '太棒了！',
    excellent: '优秀！',
    great: '很好！',
    good: '不错！',
  },

  // Arabic
  ar: {
    level: 'المستوى',
    score: 'النقاط',
    time: 'الوقت',
    hint: 'تلميح',
    hints: 'تلميحات',
    shuffle: 'خلط',
    settings: 'الإعدادات',
    coins: 'العملات',
    play: 'لعب',
    pause: 'إيقاف',
    resume: 'استمرار',
    restart: 'إعادة',
    quit: 'خروج',
    next: 'التالي',
    back: 'رجوع',
    levelComplete: 'اكتمل المستوى!',
    gameOver: 'انتهت اللعبة',
    newHighScore: 'رقم قياسي جديد!',
    wordFound: 'تم العثور على الكلمة!',
    noHintsLeft: 'لا توجد تلميحات',
    watchAdForHint: 'شاهد إعلان للتلميح',
    watchAdForCoins: 'شاهد إعلان للعملات',
    home: 'الرئيسية',
    levels: 'المستويات',
    shop: 'المتجر',
    profile: 'الملف الشخصي',
    leaderboard: 'المتصدرين',
    achievements: 'الإنجازات',
    dailyChallenge: 'التحدي اليومي',
    sound: 'الصوت',
    music: 'الموسيقى',
    vibration: 'الاهتزاز',
    notifications: 'الإشعارات',
    language: 'اللغة',
    removeAds: 'إزالة الإعلانات',
    buyCoins: 'شراء العملات',
    buyHints: 'شراء التلميحات',
    restore: 'استعادة المشتريات',
    dailyReward: 'المكافأة اليومية',
    claimReward: 'استلام',
    comeBackTomorrow: 'عد غداً!',
    bonusCoins: 'عملات إضافية',
    freeHint: 'تلميح مجاني',
    loading: 'جاري التحميل...',
    enterWord: 'أدخل الكلمة...',
    congratulations: 'تهانينا!',
    amazing: 'مذهل!',
    excellent: 'ممتاز!',
    great: 'رائع!',
    good: 'جيد!',
  },

  // Hindi
  hi: {
    level: 'स्तर',
    score: 'स्कोर',
    time: 'समय',
    hint: 'संकेत',
    hints: 'संकेत',
    shuffle: 'फेरबदल',
    settings: 'सेटिंग्स',
    coins: 'सिक्के',
    play: 'खेलें',
    pause: 'रोकें',
    resume: 'जारी रखें',
    restart: 'पुनः आरंभ',
    quit: 'बाहर',
    next: 'अगला',
    back: 'वापस',
    levelComplete: 'स्तर पूरा!',
    gameOver: 'खेल समाप्त',
    newHighScore: 'नया उच्च स्कोर!',
    wordFound: 'शब्द मिला!',
    noHintsLeft: 'कोई संकेत नहीं बचा',
    watchAdForHint: 'संकेत के लिए विज्ञापन देखें',
    watchAdForCoins: 'सिक्कों के लिए विज्ञापन देखें',
    home: 'होम',
    levels: 'स्तर',
    shop: 'दुकान',
    profile: 'प्रोफ़ाइल',
    leaderboard: 'लीडरबोर्ड',
    achievements: 'उपलब्धियां',
    dailyChallenge: 'दैनिक चुनौती',
    sound: 'ध्वनि',
    music: 'संगीत',
    vibration: 'कंपन',
    notifications: 'सूचनाएं',
    language: 'भाषा',
    removeAds: 'विज्ञापन हटाएं',
    buyCoins: 'सिक्के खरीदें',
    buyHints: 'संकेत खरीदें',
    restore: 'खरीदारी पुनर्स्थापित',
    dailyReward: 'दैनिक पुरस्कार',
    claimReward: 'प्राप्त करें',
    comeBackTomorrow: 'कल वापस आएं!',
    bonusCoins: 'बोनस सिक्के',
    freeHint: 'मुफ्त संकेत',
    loading: 'लोड हो रहा है...',
    enterWord: 'शब्द दर्ज करें...',
    congratulations: 'बधाई हो!',
    amazing: 'अद्भुत!',
    excellent: 'उत्कृष्ट!',
    great: 'शानदार!',
    good: 'अच्छा!',
  },
};

// Language names for display
export const languageNames: Record<SupportedLanguage, string> = {
  en: 'English',
  it: 'Italiano',
  es: 'Español',
  fr: 'Français',
  de: 'Deutsch',
  pt: 'Português',
  ru: 'Русский',
  ja: '日本語',
  ko: '한국어',
  zh: '中文',
  ar: 'العربية',
  hi: 'हिन्दी',
};

// Language flags for display
export const languageFlags: Record<SupportedLanguage, string> = {
  en: '🇬🇧',
  it: '🇮🇹',
  es: '🇪🇸',
  fr: '🇫🇷',
  de: '🇩🇪',
  pt: '🇵🇹',
  ru: '🇷🇺',
  ja: '🇯🇵',
  ko: '🇰🇷',
  zh: '🇨🇳',
  ar: '🇸🇦',
  hi: '🇮🇳',
};

// RTL languages
export const rtlLanguages: SupportedLanguage[] = ['ar'];

// Get translation
export const getTranslation = (language: SupportedLanguage): Translations => {
  return translations[language] || translations.en;
};

// Check if language is RTL
export const isRTL = (language: SupportedLanguage): boolean => {
  return rtlLanguages.includes(language);
};

export default translations;
